CREATE TABLE train_data (
  UID text,
  trip_creation_time timestamp,
  route_schedule_uuid text,
  route_type text,
  trip_uuid text,
  source_center text,
  source_name text,
  destination_center text,
  destination_name text,
  od_start_time timestamp,
  od_end_time timestamp,
  start_scan_to_end_scan float,
  is_cutoff boolean,
  cutoff_factor float,
  cutoff_timestamp timestamp,
  actual_distance_to_destination float,
  osrm_time float,
  osrm_distance float,
  factor float,
  segment_actual_time float,
  segment_osrm_time float,
  segment_osrm_distance float,
  segment_factor float,
  PRIMARY KEY (UID)
);
