//OBTENER CARRERAS
MATCH (n:Race) RETURN n LIMIT 25

//OBTENER CIRCUITOS
MATCH (n:Circuit) RETURN n LIMIT 25

//OBTENER CONSTRUCTORES
MATCH (n:Constructor) RETURN n LIMIT 25

//OBTENER PILOTOS
MATCH (n:Driver) RETURN n LIMIT 25

//VICTORIAS FERNANDO
MATCH (a:Driver {forename: 'Fernando'})-[:WON]->(r:Race)
RETURN r.name